### ISSUE TITLE
Fails to find existing instance

### ISSUE THREAD

**Issue by josegonzalez** [nodefortytwo/amz-ssh#2]
Using amz-ssh 2.0.1:

```shell
% amz-ssh -i i-02b420c8ae9660791
FATA[0000] InvalidInstanceID.NotFound: The instance ID 'i-02b420c8ae9660791' does not exist
	status code: 400, request id: 695d0445-de4e-454a-bdfa-06d4e9c066ea
```

With ec2-instance-connect:

```shell
 % mssh i-02b420c8ae9660791
ubuntu@i-02b420c8ae9660791:~$
```

I don't have a bastion server, not sure if that is required?

**Comment by nodefortytwo** [comment]
hi @josegonzalez,
a bastion server isn't required. `amz-ssh` current defaults to `eu-central-1` maybe that is the problem?

i'll update shortly to default to `AWS_REGION` env var

**Comment by nodefortytwo** [comment]
v2.1.0 now uses the `AWS_REGION` env variable which I believe is the likely cause, please re-open if you are still having issues
